version: '3.8'

services:
  mongo1:
    build: '.'
    hostname: mongo1
    container_name: mongo1
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - 'mongodb.key'
      - '--bind_ip_all'
      - '--auth'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db/replica/mongo1:/data/db
  mongo2:
    build: '.'
    hostname: mongo2
    container_name: mongo2
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - 'mongodb.key'
      - '--bind_ip_all'
      - '--auth'
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data/db/replica/mongo2:/data/db
    depends_on:
      - mongo1
  mongo3:
    build: '.'
    hostname: mongo3
    container_name: mongo3
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - 'mongodb.key'
      - '--bind_ip_all'
      - '--auth'
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./data/db/replica/mongo3:/data/db
    depends_on:
      - mongo2
networks:
  default:
    name: mongoCluster
